### ISSUE TITLE
dupa

### ISSUE THREAD

**Issue by kamildzi** [NX49/Kiwi#1]
Database::connect(Config::SQL_HOST, Config::SQL_USER, Config::SQL_PASSWORD, Config::SQL_DATABASE);
var_dump(Account::create('dupaaa','dupa@dupa.com','dupa123'));

-------------------------------------------------------------------------------------------
/usr/bin/php "/home/kamil/Pobrane/Firefox/stud/projekt bazy⁄inżynieria/kiwi_phpstorm/Kiwi/index.php"
PHP Fatal error:  Uncaught exception 'RuntimeException' in /home/kamil/Pobrane/Firefox/stud/projekt bazy⁄inżynieria/kiwi_phpstorm/Kiwi/includes/database.php:115
Stack trace:
#0 /home/kamil/Pobrane/Firefox/stud/projekt bazy⁄inżynieria/kiwi_phpstorm/Kiwi/includes/account.php(104): Kiwi\Database::insert('accounts', Array)
#1 /home/kamil/Pobrane/Firefox/stud/projekt bazy⁄inżynieria/kiwi_phpstorm/Kiwi/index.php(16): Kiwi\Account::create('dupaaa', 'dupa@dupa.com', 'dupa123')
#2 {main}
  thrown in /home/kamil/Pobrane/Firefox/stud/projekt bazy⁄inżynieria/kiwi_phpstorm/Kiwi/includes/database.php on line 115

Process finished with exit code 255

**Comment by NX49** [comment]
database.php:114 -> var_dump($statement->errno);

**Comment by kamildzi** [comment]
/usr/bin/php "/home/kamil/Pobrane/Firefox/stud/projekt bazy⁄inżynieria/kiwi_phpstorm/Kiwi/index.php"
int(1452)
PHP Fatal error:  Uncaught exception 'RuntimeException' in /home/kamil/Pobrane/Firefox/stud/projekt bazy⁄inżynieria/kiwi_phpstorm/Kiwi/includes/database.php:116
Stack trace:
#0 /home/kamil/Pobrane/Firefox/stud/projekt bazy⁄inżynieria/kiwi_phpstorm/Kiwi/includes/account.php(104): Kiwi\Database::insert('accounts', Array)
#1 /home/kamil/Pobrane/Firefox/stud/projekt bazy⁄inżynieria/kiwi_phpstorm/Kiwi/index.php(16): Kiwi\Account::create('dupaaa', 'dupa@dupa.com', 'dupa123')
#2 {main}
  thrown in /home/kamil/Pobrane/Firefox/stud/projekt bazy⁄inżynieria/kiwi_phpstorm/Kiwi/includes/database.php on line 116

Process finished with exit code 255

**Comment by NX49** [comment]
SQL: `card_id` -> NULL
